<a href="https://colab.research.google.com/github/Symphoen1x/LearnAI-NLP/blob/main/NLP/bag_of_words_exercise_questions%20(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TO-DO:
1. melanjutkan bagian selanjutnya

# OUtput
1. 25/08: import dataset, convert label

### Bag of words: Exercises


- In this Exercise, you are going to classify whether a given movie review is **positive or negative**.
- you are going to use Bag of words for pre-processing the text and apply different classification algorithms.
- Sklearn CountVectorizer has the inbuilt implementations for Bag of Words.

### **About Data: IMDB Dataset**

Credits: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews?resource=download


- This data consists of two columns.
        - review
        - sentiment
- Reviews are the statements given by users after watching the movie.
- sentiment feature tells whether the given review is positive or negative.

##Import necessary libraries

In [1]:
# for BOW preprocessing
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# for classification
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

# for evaluation
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

##Kaggle Authorization

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.6.17)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.7.4)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.5)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.8)

In [3]:
!mv path/to/downloads/kaggle(2).json /content/

/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `mv path/to/downloads/kaggle(2).json /content/'

In [4]:
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle(2).json

cp: cannot stat 'kaggle.json': No such file or directory
/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `chmod 600 ~/.kaggle/kaggle(2).json'

In [5]:
!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
License(s): other
Downloading imdb-dataset-of-50k-movie-reviews.zip to /content
 66% 17.0M/25.7M [00:00<00:00, 79.1MB/s]
100% 25.7M/25.7M [00:00<00:00, 93.2MB/s]

In [6]:
!unzip imdb-dataset-of-50k-movie-reviews.zip

Archive:  imdb-dataset-of-50k-movie-reviews.zip
  inflating: IMDB Dataset.csv

##Import dataset

In [7]:
#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable
df = pd.read_csv('IMDB Dataset.csv')

#2. print the shape of the data
print(df.shape)

#3. print top 5 datapoints
df.head()

(50000, 2)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
df.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [9]:
#check the distribution of 'Category' and see whether the Target labels are balanced or not.
df.sentiment.value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

##Creating a new column "Category" which represent 1 if the sentiment is positive or 0 if it is negative

In [10]:
df['positive'] = df['sentiment'].apply(lambda x: 1 if x=='positive' else 0)

# def spam_or_not(x):
#     if x == 'positive':
#         return 1
#     else:
#         return 0

# df['positive'] = df['Category'].apply(spam_or_not)
df.head()

                                              review sentiment  positive
0  One of the other reviewers has mentioned that ...  positive         1
1  A wonderful little production. <br /><br />The...  positive         1
2  I thought this was a wonderful way to spend ti...  positive         1
3  Basically there's a family where a little boy ...  negative         0
4  Petter Mattei's "Love in the Time of Money" is...  positive         1

In [11]:
df.tail()

                                                  review sentiment  positive
49995  I thought this movie did a down right good job...  positive         1
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative         0
49997  I am a Catholic taught in parochial elementary...  negative         0
49998  I'm going to have to disagree with the previou...  negative         0
49999  No one expects the Star Trek movies to be high...  negative         0

In [12]:
df.sentiment.value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

##Do the 'train-test' splitting with test size of 20%

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.review, df.positive, test_size=0.2)

## Exercise-1

1. using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative.

**Note:**
- use CountVectorizer for pre-processing the text.

- use **Random Forest** as the classifier with estimators as 50 and criterion as entropy.
- print the classification report.

**References**:

- https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [15]:
# Create bag of words representation using CountVectorizer
cv = CountVectorizer()
fit_train = cv.fit_transform(X_train.values)
# fit_train.toarray() #ketika proses mengubah ke array(readable) ini di run kemungkinan ke riset runtimenya karena gede banget. so, fokus ke tujuan exercise!
# list_feature = cv.get_feature_names_out()
# print(list_feature)


# Train the Random Forest model
model = RandomForestClassifier(n_estimators=50, criterion='entropy')


# fit with X_train and y_train
model.fit(fit_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=50)

In [16]:
x_test_cv = cv.transform(X_test)

In [19]:
# get the predictions for X_test and store it in y_pred
y_pred = model.predict(x_test_cv)
# print the classfication report
print(classification_report(y_test, y_pred))

# create a pipeline object
clf = Pipeline([
    ('vectorizer', cv),
    ('random_forest', model)
])
print(clf)

              precision    recall  f1-score   support

           0       0.84      0.85      0.84      5072
           1       0.84      0.83      0.84      4928

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('random_forest',
                 RandomForestClassifier(criterion='entropy', n_estimators=50))])

## Exercise-2

1. using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..

**Note:**
- use CountVectorizer for pre-processing the text.
- use **KNN** as the classifier with n_neighbors of 10 and metric as 'euclidean'.
- print the classification report.

**References**:

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
- https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [20]:
# Train the Random Forest model
model2 = KNeighborsClassifier(n_neighbors=10, metric='euclidean')


# fit with X_train and y_train
model2.fit(fit_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=10)

In [23]:
# create a pipeline object
clfs = Pipeline([
    ('vectorizer', cv),
    ('KNN', model2)
])
print(clfs)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('KNN',
                 KNeighborsClassifier(metric='euclidean', n_neighbors=10))])

In [24]:
# get the predictions for X_test and store it in y_pred
x_test_cv = cv.transform(X_test)
y_pred = model2.predict(x_test_cv)
# print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.66      0.67      0.66      5072
           1       0.65      0.64      0.64      4928

    accuracy                           0.65     10000
   macro avg       0.65      0.65      0.65     10000
weighted avg       0.65      0.65      0.65     10000

## Exercise-3

1. using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..

**Note:**
- use CountVectorizer for pre-processing the text.
- use **Multinomial Naive Bayes** as the classifier.
- print the classification report.

**References**:

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
- https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html

In [ ]:
#1. create a pipeline object



#2. fit with X_train and y_train



#3. get the predictions for X_test and store it in y_pred



#4. print the classfication report

## Can you write some observations of why model like KNN fails to produce good results unlike RandomForest and MultinomialNB?

## [**Solution**](./bag_of_words_exercise_solutions.ipynb)